version: '3.0'

services:
  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    networks:
      - backend

#  mysql:
#    image: mysql:5.7
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - backend
#
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    environment:
#      - VIRTUAL_HOST=phpmyadmin.local
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    networks:
#      - frontend
#      - backend


networks:
  frontend:
    external:
      name: laravel_docker_proxy
  backend:
